/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

package com.zex.zexbrowse.ui

import android.content.Intent
import android.net.Uri
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.animation.AnimatedContent
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.LazyRow
import androidx.compose.foundation.lazy.items
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.alpha
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.ImeAction
import androidx.compose.ui.unit.dp
import androidx.compose.ui.viewinterop.AndroidView
import androidx.lifecycle.viewmodel.compose.viewModel
import com.zex.zexbrowse.browser.BrowserTab
import com.zex.zexbrowse.browser.BrowserViewModel
import com.zex.zexbrowse.download.DownloadManager
import com.zex.zexbrowse.data.SettingsStore
import com.zex.zexbrowse.data.UpdateChecker
import kotlinx.coroutines.launch
import kotlinx.coroutines.Dispatchers
import org.mozilla.geckoview.GeckoView
import java.time.Instant

enum class Page { HOME, BROWSER, TABS, SETTINGS, ABOUT }
data class QuickSite(val title: String, val url: String, val icon: String)
private val defaults = listOf(QuickSite("GitHub", "https://github.com", "⌘"), QuickSite("Google", "https://www.google.com", "G"), QuickSite("Mozilla", "https://www.mozilla.org", "M"), QuickSite("Wikipedia", "https://www.wikipedia.org", "W"))

@Composable fun ZexBrowseApp() {
    val context = LocalContext.current; val settingsStore = remember { SettingsStore(context) }; val settings by settingsStore.settings.collectAsState(initial = com.zex.zexbrowse.data.BrowserSettings()); val scope = rememberCoroutineScope()
    val viewModel: BrowserViewModel = viewModel(); viewModel.browserSettings = settings; var page by rememberSaveable { mutableStateOf(Page.HOME) }
    val useDark = when (settings.darkMode) { "dark" -> true; "light" -> false; else -> isSystemInDarkTheme() }
    val scheme = if (settings.dynamicColor && android.os.Build.VERSION.SDK_INT >= 31) if (useDark) dynamicDarkColorScheme(context) else dynamicLightColorScheme(context) else if (useDark) darkColorScheme() else lightColorScheme()
    MaterialTheme(colorScheme = scheme) { Surface { AnimatedContent(page, label = "page") { target -> when (target) { Page.HOME -> HomeScreen(onOpen = { viewModel.load(it); page = Page.BROWSER }, onSettings = { page = Page.SETTINGS }); Page.BROWSER -> BrowserScreen(viewModel, onHome = { page = Page.HOME }, onTabs = { page = Page.TABS }, onSettings = { page = Page.SETTINGS }); Page.TABS -> TabOverview(viewModel, onBack = { page = Page.BROWSER }); Page.SETTINGS -> SettingsScreen(settings, { scope.launch { settingsStore.mode(it) } }, { scope.launch { settingsStore.dynamic(it) } }, { scope.launch { settingsStore.cookies(it) } }, { scope.launch { settingsStore.apkHash(it) } }, { scope.launch { settingsStore.userAgentMode(it) } }, { scope.launch { settingsStore.customUserAgent(it) } }, onAbout = { page = Page.ABOUT }, onBack = { page = Page.HOME }); Page.ABOUT -> AboutScreen { page = Page.SETTINGS } } } } }
}

@Composable private fun Glass(modifier: Modifier = Modifier, content: @Composable RowScope.() -> Unit) = Surface(modifier = modifier, color = MaterialTheme.colorScheme.surface.copy(alpha = .82f), tonalElevation = 3.dp, shape = MaterialTheme.shapes.extraLarge) { Row(verticalAlignment = Alignment.CenterVertically, content = content) }
@Composable private fun HomeScreen(onOpen: (String) -> Unit, onSettings: () -> Unit) { var query by rememberSaveable { mutableStateOf("") }; var sites by remember { mutableStateOf(defaults) }; var editor by remember { mutableStateOf(false) }
    Scaffold(topBar = { CenterAlignedTopAppBar(title = { Text("ZexBrowse", fontWeight = FontWeight.Bold) }, actions = { IconButton(onClick = onSettings) { Icon(Icons.Default.Settings, "设置") } }) }) { padding -> Column(Modifier.fillMaxSize().padding(padding).padding(20.dp), horizontalAlignment = Alignment.CenterHorizontally) { Spacer(Modifier.height(48.dp)); Glass(Modifier.fillMaxWidth()) { OutlinedTextField(query, { query = it }, Modifier.weight(1f), placeholder = { Text("搜索或输入网址") }, singleLine = true, trailingIcon = { if (query.isNotBlank()) IconButton({ query = "" }) { Icon(Icons.Default.Close, "清空") } }, keyboardOptions = androidx.compose.foundation.text.KeyboardOptions(imeAction = ImeAction.Go), keyboardActions = androidx.compose.foundation.text.KeyboardActions(onGo = { if (query.isNotBlank()) onOpen(query) })) }; IconButton({ if (query.isNotBlank()) onOpen(query) }) { Icon(Icons.Default.Search, "打开") } }; Spacer(Modifier.height(32.dp)); Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) { Text("快捷访问", style = MaterialTheme.typography.titleMedium); TextButton({ editor = true }) { Text("编辑") } }; QuickGrid(sites, onOpen, { sites = defaults }); if (editor) QuickSiteDialog(sites, { sites = it; editor = false }, { editor = false }) } }
}
@Composable private fun QuickGrid(sites: List<QuickSite>, onOpen: (String) -> Unit, onRestore: () -> Unit) { LazyColumn(verticalArrangement = Arrangement.spacedBy(10.dp)) { items(sites.chunked(2)) { row -> Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(10.dp)) { row.forEach { site -> ElevatedCard(Modifier.weight(1f).height(92.dp).clickable { onOpen(site.url) }) { Column(Modifier.padding(14.dp)) { Text(site.icon, style = MaterialTheme.typography.headlineSmall); Text(site.title) } } }; repeat(2 - row.size) { Spacer(Modifier.weight(1f)) } } }; item { TextButton(onRestore, Modifier.fillMaxWidth()) { Text("恢复默认快捷站点") } } } }
@Composable private fun QuickSiteDialog(sites: List<QuickSite>, onConfirm: (List<QuickSite>) -> Unit, onDismiss: () -> Unit) { var title by remember { mutableStateOf("") }; var url by remember { mutableStateOf("") }; AlertDialog(onDismissRequest = onDismiss, title = { Text("添加快捷站点") }, text = { Column { OutlinedTextField(title, { title = it }, label = { Text("名称") }); OutlinedTextField(url, { url = it }, label = { Text("网址") }) } }, confirmButton = { TextButton({ if (title.isNotBlank() && url.isNotBlank()) onConfirm(sites + QuickSite(title, url, title.take(1))) }) { Text("添加") } }, dismissButton = { TextButton(onDismiss) { Text("取消") } }) }

@Composable private fun BrowserScreen(vm: BrowserViewModel, onHome: () -> Unit, onTabs: () -> Unit, onSettings: () -> Unit) { val tabs by vm.tabs.collectAsState(); val selectedId by vm.selectedId.collectAsState(); val tab = tabs.firstOrNull { it.id == selectedId }; var input by remember(tab?.id) { mutableStateOf(tab?.url.orEmpty()) }; var downloadUrl by remember { mutableStateOf<String?>(null) }; var expectedHash by remember { mutableStateOf("") }; var hashResult by remember { mutableStateOf<String?>(null) }; var newTabDialog by remember { mutableStateOf(false) }; val context = LocalContext.current; val scope = rememberCoroutineScope(); val targetLauncher = rememberLauncherForActivityResult(ActivityResultContracts.CreateDocument("application/octet-stream")) { target -> if (target != null && downloadUrl != null) scope.launch { val actual = DownloadManager(context).download(downloadUrl!!, target); hashResult = if (expectedHash.isBlank()) "SHA-256：$actual" else if (actual.equals(expectedHash.trim(), true)) "SHA-256 匹配" else "SHA-256 不匹配（文件损坏/篡改）" } }
    vm.onExternalDownload = { downloadUrl = it }
    Scaffold(topBar = { Glass(Modifier.fillMaxWidth().padding(10.dp)) { OutlinedTextField(input, { input = it }, Modifier.weight(1f), placeholder = { Text("搜索或输入网址") }, singleLine = true, trailingIcon = { if (input.isNotBlank()) IconButton({ input = "" }) { Icon(Icons.Default.Close, "清空") } }); IconButton({ vm.load(input) }) { Icon(Icons.Default.ArrowForward, "打开") } } }, bottomBar = { Glass(Modifier.fillMaxWidth().padding(10.dp)) { IconButton({ vm.back() }, enabled = tab?.canGoBack == true) { Icon(Icons.Default.ArrowBack, "后退") }; IconButton({ vm.forward() }, enabled = tab?.canGoForward == true) { Icon(Icons.Default.ArrowForward, "前进") }; IconButton({ vm.reload() }) { Icon(Icons.Default.Refresh, "刷新") }; IconButton({ newTabDialog = true }) { Icon(Icons.Default.Add, "新建标签") }; IconButton(onTabs) { BadgedBox({ Badge { Text(tabs.size.toString()) } }) { Icon(Icons.Default.Tab, "标签") } }; IconButton(onSettings) { Icon(Icons.Default.MoreVert, "菜单") } } }) { padding -> Column(Modifier.fillMaxSize().padding(padding)) { LazyRow(Modifier.fillMaxWidth().padding(horizontal = 8.dp)) { items(tabs, key = { it.id }) { item -> AssistChip(onClick = { vm.select(item.id) }, label = { Text(item.title, maxLines = 1) }, leadingIcon = { if (item.id == selectedId) Icon(Icons.Default.Check, null) else null }) } }; if (tab != null) { if (tab.loading) LinearProgressIndicator(progress = { tab.progress / 100f }, Modifier.fillMaxWidth()); AndroidView(factory = { GeckoView(it) }, update = { it.setSession(tab.session) }, modifier = Modifier.fillMaxSize()); if (tab.failed) Text("页面加载失败，请检查网络后重试。", Modifier.align(Alignment.CenterHorizontally).padding(12.dp), color = MaterialTheme.colorScheme.error) } } }
    if (newTabDialog) AlertDialog(onDismissRequest = { newTabDialog = false }, title = { Text("新建标签") }, text = { Text("无痕标签不会保存浏览历史、Cookie 或缓存。") }, confirmButton = { TextButton({ vm.newTab(); newTabDialog = false; onTabs() }) { Text("普通标签") } }, dismissButton = { TextButton({ vm.newTab(incognito = true); newTabDialog = false; onTabs() }) { Text("无痕标签") } }); if (downloadUrl != null) DownloadDialog(downloadUrl!!, { name, expected -> expectedHash = expected; targetLauncher.launch(name); downloadUrl = null }, { downloadUrl = null }); if (hashResult != null) AlertDialog(onDismissRequest = { hashResult = null }, title = { Text("APK 哈希校验") }, text = { Text(hashResult!!) }, confirmButton = { TextButton({ hashResult = null }) { Text("确定") } })

@Composable private fun TabOverview(vm: BrowserViewModel, onBack: () -> Unit) { val tabs by vm.tabs.collectAsState(); Scaffold(topBar = { TopAppBar(title = { Text("全部标签") }, navigationIcon = { IconButton(onBack) { Icon(Icons.Default.ArrowBack, "返回") } }, actions = { TextButton({ vm.closeAll() }) { Text("关闭全部") } }) }) { padding -> LazyColumn(Modifier.fillMaxSize().padding(padding).padding(16.dp), verticalArrangement = Arrangement.spacedBy(10.dp)) { items(tabs, key = { it.id }) { tab -> ElevatedCard(Modifier.fillMaxWidth().clickable { vm.select(tab.id); onBack() }) { Row(Modifier.padding(16.dp), verticalAlignment = Alignment.CenterVertically) { Surface(Modifier.size(52.dp), color = MaterialTheme.colorScheme.secondaryContainer, shape = MaterialTheme.shapes.medium) { Box(contentAlignment = Alignment.Center) { Icon(Icons.Default.Language, null) } }; Spacer(Modifier.width(14.dp)); Column(Modifier.weight(1f)) { Text(tab.title, maxLines = 1); Text(tab.url.ifEmpty { "新标签页" }, maxLines = 1, style = MaterialTheme.typography.bodySmall) }; IconButton({ vm.close(tab.id) }) { Icon(Icons.Default.Close, "关闭") } } } } } } }
@Composable private fun SettingsScreen(settings: com.zex.zexbrowse.data.BrowserSettings, setMode: (String) -> Unit, setDynamic: (Boolean) -> Unit, setCookie: (Boolean) -> Unit, setApkHash: (Boolean) -> Unit, setUserAgentMode: (String) -> Unit, setCustomUserAgent: (String) -> Unit, onAbout: () -> Unit, onBack: () -> Unit) {
    val userAgentLabels = mapOf("geckoview" to "默认 GeckoView", "android_chrome" to "Android Chrome", "desktop_chrome" to "桌面 Chrome", "desktop_firefox" to "桌面 Firefox", "custom" to "自定义")
    Scaffold(topBar = { TopAppBar(title = { Text("设置") }, navigationIcon = { IconButton(onBack) { Icon(Icons.Default.ArrowBack, "返回") } }) }) { padding -> LazyColumn(Modifier.fillMaxSize().padding(padding)) { item { ListItem(headlineContent = { Text("主题") }, supportingContent = { Text("跟随系统、浅色或深色") }, trailingContent = { var expanded by remember { mutableStateOf(false) }; Box { TextButton({ expanded = true }) { Text(if (settings.darkMode == "system") "系统" else settings.darkMode) }; DropdownMenu(expanded, { expanded = false }) { listOf("system" to "跟随系统", "light" to "浅色", "dark" to "深色").forEach { (value, label) -> DropdownMenuItem(text = { Text(label) }, onClick = { setMode(value); expanded = false }) } } } }) }; item { SwitchRow("动态莫奈取色", "使用系统动态颜色", settings.dynamicColor, setDynamic) }; item { HorizontalDivider() }; item { SwitchRow("启用 Cookie", "关闭后新会话不保存 Cookie", settings.cookiesEnabled, setCookie) }; item { ListItem(headlineContent = { Text("无痕会话") }, supportingContent = { Text("通过浏览页底部新建标签按钮创建；无痕会话不保存历史、Cookie 或缓存。") }) }; item { ListItem(headlineContent = { Text("清除缓存与 Cookie") }, leadingContent = { Icon(Icons.Default.Delete, null) }, modifier = Modifier.clickable { setCookie(false); setCookie(true) }) }; item { HorizontalDivider() }; item { ListItem(headlineContent = { Text("浏览器标识") }, supportingContent = { Text("更改后仅新建标签页生效") }, trailingContent = { var expanded by remember { mutableStateOf(false) }; Box { TextButton({ expanded = true }) { Text(userAgentLabels[settings.userAgentMode] ?: "默认 GeckoView") }; DropdownMenu(expanded, { expanded = false }) { userAgentLabels.forEach { (value, label) -> DropdownMenuItem(text = { Text(label) }, onClick = { setUserAgentMode(value); expanded = false }) } } } }) }; if (settings.userAgentMode == "custom") { item { OutlinedTextField(value = settings.customUserAgent, onValueChange = setCustomUserAgent, modifier = Modifier.fillMaxWidth().padding(horizontal = 16.dp), label = { Text("自定义 User-Agent") }, supportingText = { Text("留空时使用 GeckoView 默认标识") }, singleLine = false) } }; item { SwitchRow("APK SHA-256 校验", "下载 APK 时计算哈希值", settings.apkHashEnabled, setApkHash) }; item { ListItem(headlineContent = { Text("关于 ZexBrowse") }, leadingContent = { Icon(Icons.Default.Info, null) }, modifier = Modifier.clickable(onAbout)) } } } }
@Composable private fun SwitchRow(title: String, subtitle: String, checked: Boolean, changed: (Boolean) -> Unit) = ListItem(headlineContent = { Text(title) }, supportingContent = { Text(subtitle) }, trailingContent = { Switch(checked, changed) })
@Composable private fun DownloadDialog(url: String, onDownload: (String, String) -> Unit, onDismiss: () -> Unit) { val isApk = url.substringBefore('?').endsWith(".apk", true); var expected by rememberSaveable { mutableStateOf("") }; AlertDialog(onDismissRequest = onDismiss, title = { Text("下载文件") }, text = { Column { Text(url.substringAfterLast('/').substringBefore('?').ifBlank { "download" }); if (isApk) { Spacer(Modifier.height(12.dp)); Text("APK 下载完成后将自动计算 SHA-256。", style = MaterialTheme.typography.bodySmall); OutlinedTextField(expected, { expected = it }, label = { Text("官方 SHA-256（可选）") }, supportingText = { Text("下载后会显示匹配或不匹配结果") }) } } }, confirmButton = { TextButton({ onDownload(url.substringAfterLast('/').substringBefore('?').ifBlank { "download" }, expected) }) { Text("选择保存位置") } }, dismissButton = { TextButton(onDismiss) { Text("取消") } }) }
@Composable private fun AboutScreen(onBack: () -> Unit) { val context = LocalContext.current; val scope = rememberCoroutineScope(); var checking by remember { mutableStateOf(false) }; var update by remember { mutableStateOf<com.zex.zexbrowse.data.ReleaseInfo?>(null) }; var message by remember { mutableStateOf<String?>(null) }
    Scaffold(topBar = { TopAppBar(title = { Text("关于") }, navigationIcon = { IconButton(onBack) { Icon(Icons.Default.ArrowBack, "返回") } }) }) { padding -> Column(Modifier.padding(padding).padding(24.dp), verticalArrangement = Arrangement.spacedBy(14.dp)) { Text("ZexBrowse", style = MaterialTheme.typography.headlineMedium, fontWeight = FontWeight.Bold); Text("版本 1.0.0（构建号 1）"); Text("本项目采用 Mozilla Public License 2.0 (MPL-2.0) 开源。GeckoView 及其相关组件遵循 Mozilla 的相应开源许可。Jetpack Compose、Material 3 和 AndroidX 库遵循各自许可证。", style = MaterialTheme.typography.bodyMedium); FilledTonalButton({ context.startActivity(Intent(Intent.ACTION_VIEW, Uri.parse("https://github.com/BaiXiaoTao520/ZexBrowse"))) }) { Icon(Icons.Default.OpenInNew, null); Spacer(Modifier.width(8.dp)); Text("GitHub 仓库") }; OutlinedButton({ checking = true; scope.launch(Dispatchers.IO) { runCatching { UpdateChecker().latest() }.onSuccess { release -> if (release != null && UpdateChecker().isNewer(release.version)) update = release else message = "当前已是最新版本" }.onFailure { message = "更新检查失败，请稍后重试" }; checking = false } }, enabled = !checking) { Text(if (checking) "正在检查…" else "检查更新") } } }
    update?.let { release -> AlertDialog(onDismissRequest = { update = null }, title = { Text("发现新版本 ${release.version}") }, text = { Text(release.notes.ifBlank { "暂无更新说明" }) }, confirmButton = { TextButton({ if (release.downloadUrl.isNotBlank()) context.startActivity(Intent(Intent.ACTION_VIEW, Uri.parse(release.downloadUrl))); update = null }) { Text("下载") } }, dismissButton = { TextButton({ update = null }) { Text("稍后") } }) }; message?.let { text -> AlertDialog(onDismissRequest = { message = null }, title = { Text("更新") }, text = { Text(text) }, confirmButton = { TextButton({ message = null }) { Text("确定") } }) }
}
